[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "http://sozu.io"
version = "0.4.0"
license = "AGPL-3.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
categories = ["network-programming"]

include = [
  "README.md",
  "Cargo.toml",
  "src/**/*",
]

[[bin]]
name = "sozu"

[dependencies]
mio = "^0.6"
mio-uds = "^0.6"
serde = "~1.0.2"
serde_json = "~1.0.1"
serde_derive = "~1.0.2"
nom = "^2.0"
nix  = "^0.8"
time = "^0.1.34"
clap = "^2.19.0"
slab = "^0.3.0"
libc = "^0.2"
rand = "^0.3.14"
tempfile = "^2.2"
sozu-lib = { version = "^0.4", path = "../lib" }
sozu-command-lib = { version = "^0.4", path = "../command" }

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.3.0"
procinfo = "^0.4.1"

[features]
unstable = []
use_openssl = ["sozu-lib/use_openssl"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
